---
rules:
  unpinned-uses:
    ignore: 
      - .github/workflows/lint.yml
      - /github/workspace/.github/workflows/lint.yml
      - .github/workflows/test.yml
      - /github/workspace/.github/workflows/test.yml
  excessive-permissions:
    ignore: 
      - .github/workflows/lint.yml
      - /github/workspace/.github/workflows/lint.yml
      - .github/workflows/test.yml
      - /github/workspace/.github/workflows/test.yml
  template-injection:
    ignore: 
      - .github/workflows/lint.yml
      - /github/workspace/.github/workflows/lint.yml
      - .github/workflows/test.yml
      - /github/workspace/.github/workflows/test.yml
