---
rules:
  unpinned-uses:
    ignore: 
      - workflows/lint.yml
      - workflows/test.yml
  excessive-permissions:
    ignore: 
      - workflows/lint.yml
      - workflows/test.yml
  template-injection:
    ignore: 
      - workflows/lint.yml
      - workflows/test.yml
