---
on: [push, pull_request, workflow_dispatch]

name: Lint

permissions: read-all

jobs:
  super-linter:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      checks: read
      contents: read
      deployments: read
      issues: read
      discussions: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Fix formatting with Prettier
        run: |
          npx prettier --write .github/workflows/lint.yml
          npx prettier --write .github/dependabot.yml
          npx prettier --write .github/linters/.markdown-lint.yml
          npx prettier --write .github/linters/zizmor.yaml

      - name: Lint Code Base
        uses: super-linter/super-linter@d5b0a2ab116623730dd094f15ddc1b6b25bf7b99
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
